Settings:
    # Time in seconds between each check
    Dislike-Cooldown: 60
    Admin-Permission: 'reputation.admin'

    Dislike-Reputation-Change: 0.25
    Like-Reputation-Change: 0.25

    Reputation-Color-Dislike: '&c'
    Reputation-Color-Like: '&a'

Messages:
    Dislike-Cooldown: '&cYou must wait %cooldown% seconds before you can dislike again.'
    Dislike-Message: '&cYou disliked %player%!'
    Like-Message: '&aYou liked %player%!'
    No-Permission: '&cYou do not have permission to do that.'
    No-Player-Found: '&cNo player found.'
    Invalid-Vote-Type: '&cInvalid vote type.'
    Something-Went-Wrong: '&cSomething went wrong.'
    Reputation-Status: '&aYou have a total of %reputation% reputation with %likes% likes and %dislikes% dislikes.'
    Player-Reputation: '&a%player% has a total of %reputation% reputation with %likes% likes and %dislikes% dislikes.'
    Invalid-Arguments: '&cInvalid arguments.'
