BEGIN TRANSACTION;
    CREATE TABLE IF NOT EXISTS `reputation_users`(
        `uuid` CHAR(36) NOT NULL PRIMARY KEY,
        `player_name` VARCHAR(16) NOT NULL,
        `last_like` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `last_dislike` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE IF NOT EXISTS `reputation_votes`(
        `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `uuid` CHAR(36) NOT NULL,
        `player_name` VARCHAR(16) NOT NULL,
        `target_uuid` CHAR(36) NOT NULL,
        `target_player_name` VARCHAR(16) NOT NULL,
        `vote` ENUM('LIKE', 'DISLIKE') NOT NULL,
        `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;
